export const genreOptions = [
     { label: 'Action', value: 'action' },
     { label: 'Adventure', value: 'adventure' },
     { label: 'Avant Garde', value: 'avant garde' },
     { label: 'Award Winning', value: 'award winning' },
     { label: 'Boys Love', value: 'boys love' },
     { label: 'Comedy', value: 'comedy' },
     { label: 'Drama', value: 'drama' },
     { label: 'Fantasy', value: 'fantasy' },
     { label: 'Girls Love', value: 'girls love' },
     { label: 'Gourmet', value: 'gourmet' },
     { label: 'Horror', value: 'horror' },
     { label: 'Mystery', value: 'mystery' },
     { label: 'Romance', value: 'romance' },
     { label: 'Sci-Fi', value: 'sci-Fi' },
     { label: 'Slice of Life', value: 'slice of life' },
     { label: 'Sports', value: 'sports' },
     { label: 'Supernatural', value: 'supernatural' },
     { label: 'Suspense', value: 'suspense' },
]