export const genreOptions = [
    { genre: 'Action', id: 1 },
    { genre: 'Adventure', id: 2 },
    { genre: 'Avant Garde', id: 5 },
    { genre: 'Award Winning', id: 46 },
    { genre: 'Boys Love', id: 28 },
    { genre: 'Comedy', id: 4 },
    { genre: 'Drama', id: 8 },
    { genre: 'Fantasy', id: 10 },
    { genre: 'Girls Love', id: 26 },
    { genre: 'Gourmet', id: 47 },
    { genre: 'Horror', id: 14 },
    { genre: 'Mystery', id: 7 },
    { genre: 'Romance', id: 22 },
    { genre: 'Sci-Fi', id: 24 },
    { genre: 'Slice of Life', id: 36 },
    { genre: 'Sports', id: 30 },
    { genre: 'Supernatural', id: 37 },
    { genre: 'Suspense', id: 41 },
    { genre: 'Isekai', id: 62 },
]