export const genreOptions = [
    { genre: 'Action', id: 1 },
    { genre: 'Adventure', id: 2 },
    { genre: 'Avant Garde', id: 3 },
    { genre: 'Award Winning', id: 4 },
    { genre: 'Boys Love', id: 5 },
    { genre: 'Comedy', id: 6 },
    { genre: 'Drama', id: 7 },
    { genre: 'Fantasy', id: 8 },
    { genre: 'Girls Love', id: 9 },
    { genre: 'Gourmet', id: 10 },
    { genre: 'Horror', id: 11 },
    { genre: 'Mystery', id: 12 },
    { genre: 'Romance', id: 13 },
    { genre: 'Sci-Fi', id: 14 },
    { genre: 'Slice of Life', id: 15 },
    { genre: 'Sports', id: 16 },
    { genre: 'Supernatural', id: 17 },
    { genre: 'Suspense', id: 18 },
]